spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommerce_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never

jwt:
  secret: ${JWT_SECRET:change-this-local-secret}
  expiration: 86400000

razorpay:
  key-id: ${RAZORPAY_KEY_ID:}
  key-secret: ${RAZORPAY_KEY_SECRET:}

brevo:
  api-key: ${BREVO_API_KEY:}
  sender-email: ${BREVO_SENDER_EMAIL:}